apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossgame-deployment
  labels:
    app: crosgame
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crossgame
  template:
    metadata:
      labels:
        app: crossgame
    spec:
      containers:
      - name: crossgame
        image: saboora/crossgame:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crossgame
spec:
  selector:
    app.kubernetes.io/name: crossgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020
